# Generated by Django 4.2.1 on 2023-06-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_venue_owner_alter_event_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
